### ISSUE TITLE
Safety: Cannot access "..." of a nullable value inside lambdas

### ISSUE THREAD

**Issue by restorer** [RealyUniqueName/Safety#8] opened 2018-10-29 12:23 UTC
```haxe
class Bug3 {
    public function bug() : Void {
        var s : Null<String> = ((Math.random() > 0.5) ? "A" : null);

        if (s != null) {
            // Safety: Cannot access "length" of a nullable value.
            function cb() : Int { return s.length; }
        }
    }
}
```

See https://github.com/restorer/haxe-safety-bugs/blob/master/safetybugs/Main.hx#L60 for working example.

**Comment by restorer** [comment] 2018-10-29 12:38
This is for Haxe 4.0.0-preview.5 and Safety from master.

**Comment by RealyUniqueName** [comment] 2018-10-29 12:56
This is an intended behavior. Because while created in a safe area the closure could be invoked outside of the body of that `if`.
Leaving this open to not forget to add a test case.

**Comment by restorer** [comment] 2018-10-29 15:25
That makes sense, but kotlin solve that somehow in some cases. Eg.

```kotlin
fun main(args: Array<String>) {
    // s is var (not val)
    var s : String? = if (java.util.Random().nextFloat() > 0.5) "AB" else null
    val items = listOf(1, 2, 3, 4, 5)
    
    if (s != null) {
	println(items.map { it * s.length })
    }
}
```

Haxe with Safety:

```haxe
public function bug() : Void {
    var s : Null<String> = ((Math.random() > 0.5) ? "AB" : null);
    var l = [1, 2, 3, 4, 5];

    if (s != null) {
        // Safety: Cannot access "length" of a nullable value.
        trace(l.map(function (v) { return v * s.length; }));
    }
}
```

**Comment by RealyUniqueName** [comment] 2019-01-30 11:44
fixed in https://github.com/HaxeFoundation/haxe/pull/7717

**Closed as completed by RealyUniqueName** 2019-01-30 11:44 UTC
